/**
 * @license
 * Copyright (C) Pryv https://pryv.com
 * This file is part of Pryv.io and released under BSD-Clause-3 License
 * Refer to LICENSE file
 */
// flow-typed signature: abe6d0b76ace8b02e3db9efc7df179c4
// flow-typed version: <<STUB>>/eslint-friendly-formatter_v^3.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-friendly-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-friendly-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-friendly-formatter/process' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-friendly-formatter/index' {
  declare module.exports: $Exports<'eslint-friendly-formatter'>;
}
declare module 'eslint-friendly-formatter/index.js' {
  declare module.exports: $Exports<'eslint-friendly-formatter'>;
}
declare module 'eslint-friendly-formatter/process.js' {
  declare module.exports: $Exports<'eslint-friendly-formatter/process'>;
}
